# Generated by Django 4.2.29 on 2026-03-29 02:44

from django.conf import settings
from django.db import migrations, models


def backfill_project_and_milestone_owners(apps, schema_editor):
    Need = apps.get_model("needs", "Need")
    Project = apps.get_model("projects", "Project")
    Milestone = apps.get_model("projects", "Milestone")
    User = apps.get_model("auth", "User")
    fallback = User.objects.filter(is_active=True).order_by("id").first()

    for p in Project.objects.all():
        if p.owners.exists():
            continue
        ids = []
        if p.lead_id:
            ids.append(p.lead_id)
        if p.need_id:
            try:
                n = Need.objects.get(pk=p.need_id)
                if n.created_by_id:
                    ids.append(n.created_by_id)
                ids.extend(list(n.owners.values_list("pk", flat=True)))
            except Need.DoesNotExist:
                pass
        for uid in set(ids):
            if uid:
                p.owners.add(uid)
        if not p.owners.exists() and fallback:
            p.owners.add(fallback.pk)

    for m in Milestone.objects.all():
        if m.owners.exists():
            continue
        ids = []
        if m.assigned_to_id:
            ids.append(m.assigned_to_id)
        try:
            proj = Project.objects.get(pk=m.project_id)
            if proj.lead_id:
                ids.append(proj.lead_id)
            ids.extend(list(proj.owners.values_list("pk", flat=True)))
        except Project.DoesNotExist:
            pass
        for uid in set(ids):
            if uid:
                m.owners.add(uid)
        if not m.owners.exists() and fallback:
            m.owners.add(fallback.pk)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("needs", "0003_owners_accountability"),
        ("projects", "0002_projectattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="owners",
            field=models.ManyToManyField(
                help_text="At least one registered user accountable for this milestone.",
                related_name="owned_milestones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owners",
            field=models.ManyToManyField(
                help_text="At least one registered user accountable for delivery and approvals.",
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_project_and_milestone_owners, migrations.RunPython.noop),
    ]
