# Generated by Django 4.2.29 on 2026-03-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_owners_accountability"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="students_impacted",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Estimated residents / learners served (for impact scorecard). Leave blank if unknown.",
                null=True,
                verbose_name="Students / residents impacted",
            ),
        ),
    ]
