# Generated by Django 4.2.29 on 2026-03-29 03:21

import apps.projects.attachments
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_students_impacted_scorecard"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="completion_proof",
            field=models.FileField(
                blank=True,
                help_text="Required before marking complete when a funding tranche % is set. Evidence for governance.",
                null=True,
                upload_to=apps.projects.attachments.milestone_proof_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "xlsx",
                            "jpg",
                            "jpeg",
                            "png",
                        ]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="completion_proof_original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="milestone",
            name="next_tranche_budget_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="% of total project budget unlocked for the next phase after this milestone is completed (with proof). Governance must approve before it counts as released. Use 0 if no tranche at this gate.",
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="tranche_governance_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "N/A (no tranche)"),
                    ("awaiting_governance", "Awaiting governance release"),
                    ("released", "Tranche released"),
                    ("rejected", "Tranche rejected"),
                ],
                default="not_applicable",
                max_length=32,
            ),
        ),
    ]
