# Generated by Django 4.2.29 on 2026-03-28 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("corporate", "Corporate"),
                            ("department", "Department"),
                            ("csr_partner", "CSR partner"),
                            ("govt", "Government"),
                        ],
                        default="department",
                        max_length=32,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("india", "India"),
                            ("us", "United States"),
                            ("other", "Other"),
                        ],
                        default="india",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stakeholder_type",
                    models.CharField(
                        choices=[
                            ("foundation_admin", "Foundation Admin"),
                            ("hod", "HOD / Dean"),
                            ("donor", "Donor"),
                            ("project_lead", "Project Lead"),
                            ("volunteer", "Volunteer"),
                            ("finance_controller", "Finance Controller"),
                            ("governance", "Governance Team"),
                            ("auditor", "Auditor"),
                        ],
                        default="volunteer",
                        max_length=32,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("india", "India"),
                            ("us", "United States"),
                            ("other", "Other"),
                        ],
                        default="india",
                        max_length=16,
                    ),
                ),
                ("email_opt_in", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="stakeholders.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
