# Generated by Django 4.2.29 on 2026-03-29 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stakeholders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="needs_persona_assignment",
            field=models.BooleanField(
                default=False,
                help_text="True when imported or created without confirmed personas — show in governance roster until cleared.",
            ),
        ),
        migrations.CreateModel(
            name="UserStakeholderPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "persona_type",
                    models.CharField(
                        choices=[
                            ("foundation_admin", "Foundation Admin"),
                            ("hod", "HOD / Dean"),
                            ("donor", "Donor"),
                            ("project_lead", "Project Lead"),
                            ("volunteer", "Volunteer"),
                            ("finance_controller", "Finance Controller"),
                            ("governance", "Governance Team"),
                            ("auditor", "Auditor"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholder_personas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id", "persona_type"],
            },
        ),
        migrations.AddConstraint(
            model_name="userstakeholderpersona",
            constraint=models.UniqueConstraint(
                fields=("user", "persona_type"), name="uniq_user_stakeholder_persona"
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _backfill_personas(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _backfill_personas(apps, schema_editor):
    UserProfile = apps.get_model("stakeholders", "UserProfile")
    UserStakeholderPersona = apps.get_model("stakeholders", "UserStakeholderPersona")
    for p in UserProfile.objects.select_related("user").iterator():
        UserStakeholderPersona.objects.get_or_create(
            user_id=p.user_id,
            persona_type=p.stakeholder_type,
        )
