# Generated by Django 4.2.29 on 2026-03-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholders", "0002_user_personas_and_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUserRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "batch_year",
                    models.PositiveSmallIntegerField(
                        help_text="Year you graduated / passed out (batch)."
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number.", max_length=32),
                ),
                ("address", models.TextField(help_text="Mailing or contact address.")),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="Optional public LinkedIn profile URL."
                    ),
                ),
                (
                    "desired_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of stakeholder role codes requested (e.g. donor, volunteer).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (admin only)."
                    ),
                ),
            ],
            options={
                "verbose_name": "pending user registration",
                "verbose_name_plural": "pending user registrations",
                "ordering": ["-created_at"],
            },
        ),
    ]
