# Generated by Django 4.2.29 on 2026-03-29 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("funding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributions",
                to="events.event",
            ),
        ),
    ]
