# Generated by Django 4.2.29 on 2026-03-29 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("funding", "0002_contribution_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="communication_capture_url",
            field=models.URLField(
                blank=True,
                help_text="Optional link to stored correspondence (e.g. S3 object URL).",
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="receipt_sent",
            field=models.BooleanField(
                default=False,
                help_text="Tax/acknowledgment receipt emailed or posted to donor.",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="receipt_sent_date",
            field=models.DateField(
                blank=True, help_text="When the receipt was sent (optional).", null=True
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="volunteer_lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Volunteer or project lead stewarding this donor relationship (e.g. HNI).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributions_volunteer_lead",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
