# Generated by Django 4.2.29 on 2026-03-29 02:44

from django.conf import settings
from django.db import migrations, models


def backfill_expense_owners(apps, schema_editor):
    Expense = apps.get_model("funding", "Expense")
    User = apps.get_model("auth", "User")
    fallback = User.objects.filter(is_active=True).order_by("id").first()
    for e in Expense.objects.all():
        if e.owners.exists():
            continue
        if e.requested_by_id:
            e.owners.add(e.requested_by_id)
        elif fallback:
            e.owners.add(fallback.pk)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("funding", "0003_contribution_receipt_comm_volunteer_lead"),
        ("projects", "0003_owners_accountability"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="owners",
            field=models.ManyToManyField(
                help_text="Registered users accountable for this expense / approval thread (e.g. requester + finance).",
                related_name="owned_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_expense_owners, migrations.RunPython.noop),
    ]
