# Generated by Django 4.2.29 on 2026-03-28 21:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stakeholders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "funding_model",
                    models.CharField(
                        choices=[("pooled", "Pooled"), ("anchor", "Anchor")],
                        default="pooled",
                        max_length=16,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("india", "India"),
                            ("us", "United States"),
                            ("both", "Both"),
                        ],
                        default="india",
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("department", "Department"),
                            ("cross_cutting", "Cross-cutting"),
                        ],
                        default="department",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("cataloged", "Cataloged"),
                            ("pending_governance", "Pending governance"),
                            ("matched", "Matched"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("target_currency", models.CharField(default="INR", max_length=8)),
                ("requires_governance_approval", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="needs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="needs",
                        to="stakeholders.organization",
                    ),
                ),
                (
                    "matched_donors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="matched_needs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
