# Generated by Django 4.2.29 on 2026-03-29 02:44

from django.conf import settings
from django.db import migrations, models


def backfill_need_owners(apps, schema_editor):
    Need = apps.get_model("needs", "Need")
    User = apps.get_model("auth", "User")
    fallback = User.objects.filter(is_active=True).order_by("id").first()
    for n in Need.objects.all():
        if n.owners.exists():
            continue
        uid = n.created_by_id or (fallback.pk if fallback else None)
        if uid:
            n.owners.add(uid)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("needs", "0002_needattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="need",
            name="owners",
            field=models.ManyToManyField(
                help_text="At least one registered user accountable for this need (governance, delivery).",
                related_name="owned_needs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_need_owners, migrations.RunPython.noop),
    ]
